# Generated by Django 5.1.2 on 2024-10-31 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledge",
            name="title",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
