# Generated by Django 5.1.1 on 2025-01-19 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_knowledge_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='vector_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
